[package]
name = "primes"
version = "0.1.0"
authors = ["Michael Komitee <mkomitee@gmail.com>"]
edition = "2018"
description = "Calculate primes with multiple algorithms."

[dependencies]
structopt = "0.2"
